#### GISC 422 T1 20
# Assignment 4
I have assembled some [demographic data for Aotearoa New Zealand](nz-2193-cau-2013.zip) (you will need to unzip this file) from the 2013 census at the Area Unit level. Use these to conduct multivariate data exploration using any of the approaches discussed here. Based on your analysis put together a report on some aspect of the demographics of the country that you think may be of interest (you can reduce the area of interest to a smaller local area if this seems appropriate). You will certainly feel that there is a need to reduce the number of data attributes in the analysis for various reasons (topic of interest, balancing the clustering analysis, etc).

In any case, your report should show clear evidence of having explored the data using the many tools we have seen this semester so far (no need to use all of them, and it's fine to focus on only the ones from this week, if you wish).

Prepare your report in R-Markdown and run it to produce a final output PDF or Word document for submission (this means I will see your code as well as the outputs!) Avoid any outputs that are just long lists of data (like this file includes), as these are not very informative (you can do this by prefixing the code chunk with ````{r, results=FALSE}`.

Submit your report to the dropbox provided on Blackboard by **22 June**.
